name: Github Action
on: [push, pull_request]
jobs:
  Test_Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'blub'
  Compile_ts_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -g typescript
      - run: npm i --save-dev @types/node
      - name: tsc
        run: tsc